name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: []
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-12
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: |
          git clone "https://chromium.googlesource.com/chromium/tools/depot_tools.git"
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
      - run: fetch --help
