name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone "https://chromium.googlesource.com/chromium/tools/depot_tools.git"
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
          
      - name: Fetch Chromium Source Code
        run: |
          cp gclient_config .gclient
          gclient sync --no-history
          
      - name: Build Chromium Cronet
        working-directory: ./src
        run: |
          gn gen out/Cronet
          ninja -C out/Cronet cronet_package
          
      - name: remove obj files
        run: rm -rf ./src/out/Cronet/obj
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: ./src/out/Cronet/
