name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-12
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: |
          git clone "https://chromium.googlesource.com/chromium/tools/depot_tools.git"
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
      - name: Fetch Chromium Source Code
        run: |
          mkdir chromium
          cd chromium
          fetch --no-history chromium
      - name: Build Chromium Cronet
        working-directory: ./chromium
        run: |
          gn gen out/Cronet
          ninja -C out/Cronet cronet_package
