name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone "https://chromium.googlesource.com/chromium/tools/depot_tools.git"
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
      - name: Fetch Chromium Source Code
        run: |
          mkdir chromium
          cp gclient_config .gclient
          cd chromium
          echo "gclient sync --no-history"
#       - name: Build Chromium Cronet
#         working-directory: ./chromium
#         run: |
#           gn gen out/Cronet
#           ninja -C out/Cronet cronet_package
